Support Go
kyuridenamida/atcoder-tools pull request #181
Opened 2020-01-04 13:50 UTC by nu50218

Go言語のCodeGeneratorを書きました。あまりPythonに慣れていないのでおかしな部分があったらすみません。

2020-01-04 13:52 UTC, nu50218 commented on atcodertools/codegen/code_generators/go.py
> +    def _indent(self, depth):
gofmtという標準のフォーマッターではインデントがタブなので、デフォルトでタブを使用したかったんですが、読んだ限りLanguageのindent_typeがデフォルトで設定できなくて、スペースを使いそうに見えたのでとりあえずこう書きました。

2020-01-04 17:02 UTC, kyuridenamida commented
ありがとうございます!ちょうど最新master branchのテストが壊れてるので、修正まで少しお待ちください。別のPRで直しましたら、手元での最新masterのmergeをお願いすることになると思います。

2020-01-04 17:11 UTC, kyuridenamida commented on atcodertools/codegen/code_generators/go.py
> +            lines.append('{name} = scanner.Text()'.format(name=name))
あまりGoには詳しくないので尋ねさせてください。GoのScanner.Text()って特別なことをしないと長い文字列を読み込むときに勝手に分割して読み込んでしまうみたいな印象があります。それってどこかで対策されていたりしますか?
(https://qiita.com/tnoda_/items/b503a72eac82862d30c6)

2020-01-04 17:23 UTC, nu50218 commented on atcodertools/codegen/code_generators/go.py
> +            lines.append('{name} = scanner.Text()'.format(name=name))
ありがとうございます。
されていないです！調べて修正します。

2020-01-04 17:33 UTC, kyuridenamida commented on atcodertools/codegen/code_generators/go.py
> +    def _indent(self, depth):
spaceを使うという方針が特にあるかというとないです。なので、default_code_styleを入れるためのCodeStyle classがindent_widthしか持ってないのをindent_typeも持つように弄った上で、CodeStyleConfigのindent_type決定のlogicをindent_widthと似たような感じで書いて頂ければ良いかなと思います。

2020-01-04 17:35 UTC, kyuridenamida commented on atcodertools/codegen/code_generators/go.py
> +            lines.append('{name} = scanner.Text()'.format(name=name))
昔この問題でGoで提出してハマった記憶があります。(曖昧な記憶ですが)
https://atcoder.jp/contests/abc138/tasks/abc138_e

2020-01-04 17:49 UTC, kyuridenamida commented
@nu50218 master、おそらく治りました!今masterのbuild走ってるので走り終わったらbuild badgeが緑に変わると思います(希望的観測)。そしたら最新のmasterをお手元でmergeお願いします。

2020-01-05 02:17 UTC, nu50218 commented on atcodertools/codegen/code_generators/go.py
> +            lines.append('{name} = scanner.Text()'.format(name=name))
ScannerのBufferのサイズを、Qiitaの記事中で一気に読み込むときのサイズとしていた、10^6バイト（デフォルト:65536）にすることで対応しようと思います。（記事中ではbufio.Readerを使っていますがScannerにもサイズを設定することができます）
1MB程度のメモリを使いますが、10^6バイトを超える非常に長い文字列を読まない限り大丈夫です。
ユーザーからしてもmain関数の最初の値を弄るだけでメモリを節約or非常に長い文字列にも対応できるので問題はないと思います。

2020-01-05 03:11 UTC, nu50218 commented
masterをマージしてインデントとScanner.Text()の問題も対応できました！

2020-01-05 03:29 UTC, nu50218 commented on atcodertools/tools/templates/default_template.go
> +	const initialBufSize = 4096
4096はデフォルトのscannerの最初のバッファーのサイズで、最大maxBufSizeまでscannerがトークンのサイズに応じて自動でバッファーを大きくしてくれます

2020-01-05 10:05 UTC, kyuridenamida commented on atcodertools/tools/templates/default_template.go
> +	const initialBufSize = 4096
buffer使うなら4096よりは競プロでよくある値(10^5とか10^6とか)にしたほうが親切だったりしませんか?基本的にテンプレートが生成された後入力部分をユーザーが意識しないことが好ましいと思っています。

2020-01-05 10:06 UTC, kyuridenamida commented on atcodertools/tools/templates/default_template.go
> +	const initialBufSize = 4096
あ、なるほど!ごめんなさい完全に挙動を理解しました!失礼しました

2021-04-21 13:36 UTC, kyuridenamida commented
GithubActionsトリガーしたいのでクローズしてオープンさせてください

2021-04-21 13:36 UTC, kyuridenamida commented
あ、だめか

2021-04-21 13:41 UTC, kyuridenamida commented
すみません。masterが今かなりoutdatedな状態になっていて、もしまだコントリビュートしていただける気持ちがありましたらstable branchに対してPRを作り直してもらえたりしませんか?

2021-04-21 13:41 UTC, kyuridenamida requested changes
すみません。masterが今かなりoutdatedな状態になっていて、もしまだコントリビュートしていただける気持ちがありましたらstable branchに対してPRを作り直してもらえたりしませんか?

2021-04-21 18:13 UTC, nu50218 commented
すみません、結構masterから変わってしまっているみたいで、差分作っていただけると助かります…

2021-06-28 14:19 UTC, chaemon commented
このプルリクエストをベースに、2.*.*対応のこちらのプルリクエストを作りました。

https://github.com/kyuridenamida/atcoder-tools/pull/235

2021-06-29 05:36 UTC, nu50218 commented
@chaemon ありがとうございます！！！

2021-07-18 17:17 UTC, kyuridenamida commented
#181
これマージしたので閉じます。皆様ありがとうございました。

2021-07-18 17:17 UTC, closed without merging